### ISSUE TITLE
长星星提前结束了导出谱面

### ISSUE THREAD

**Issue by siqod** [LingFeng-bbben/MajdataView#104]
## 问题出现的位置

导出视频的问题，我也不知道算view还是算edit

## 问题描述

导出视频时最后一个键如果是长星星会让录制提前结束，不播放ap音并且最后的长星星还没结束录制先停了

## 它是怎么出现的

我最后一段写的是82,82,3v5[12:1]/7v1[16:1],1V35[4:22]/5,36,,
{1}7b,,,,,,E
然后录制就停在了1V35中间的位置
我换了首结尾是长星星的歌，也一样停早了，配置是
7b/8b,16,25,3h[256:1]/4h[256:1],,56,
{1}
5<5[4:18]/1>1[4:18],
,,,,
E

## 它可以复现吗

可以，录3遍都一样

## 可能有帮助的截图与文件

![媒体播放器 2023_4_18 13_45_34](https://user-images.githubusercontent.com/117062074/232682589-058dcb8c-e745-4ad3-9d8f-5e127d7c2732.png)
视频太大传不了

**Comment by LingFeng-bbben** [comment]
fixed in 4.2.1
