### ISSUE TITLE
预览谱面时majdataedit窗口卡住

### ISSUE THREAD

**Issue by yizhimengxin2233** [LingFeng-bbben/MajdataView#105]
## 问题出现的位置

MajdataEdit

## 问题描述

当预览一张谱面（无论有多少物件）时，若下方预览条缩放比太大（就是缩的很小），预览时majdataedit窗口就会卡住（但可以播放音频，viewer可以正常预览），恢复时间有长有短，严重时需要任务管理器强制终止。
（注:旧版本使用时没有这个问题，个人猜测可能是音频波形的问题。物件越多卡死可能性越大，放大倍率越大可能性越小.。导出视频时不会出现该问题）
## 它是怎么出现的

如问题描述
（注：如放大至最大时预览就不会卡住）

## 它可以复现吗

可以

## 可能有帮助的截图与文件
![image](https://user-images.githubusercontent.com/58097884/235410559-a5dff570-8540-4405-8c7e-850688a8f268.png)

[谱面.zip](https://github.com/LingFeng-bbben/MajdataView/files/11363650/default.zip)

**Comment by LingFeng-bbben** [comment]
fixed in 4.2.1
