### ISSUE TITLE
MajdataEdit freeze upon pressing play button

### ISSUE THREAD

**Issue by lomotos10** [LingFeng-bbben/MajdataView#107]
## Where the problem occurs?

MajdataEdit

## Description

- MajdataEdit freezes upon playing the play button.
  - After about 1 minute, the alert box `Please make sure MajdataView is open and port 8013 is available` appears.
- `Open`ing an existing `maidata.txt` file does nothing.

## How did it occurs?

Version: v4.2.1

Pressing the play button results in the freeze.

## Can it be repeated?

Reproducible every time I restart the MajdataEdit

## Screenshot and files that may helped

![image](https://github.com/LingFeng-bbben/MajdataView/assets/48435475/d68ddb6e-0096-47e1-b1a6-0385c637d3b7)

**Comment by lomotos10** [comment]
Fixed by rebooting the computer enough times :( whoops

**Comment by XajilX** [comment]
Google 了一下, 可能与 Hyper-V 有关
Hyper-V 会在 TCP 动态端口范围中随机选择一部分端口进行保留
解决方法是缩小动态端口范围, 用管理员权限运行如下命令: 
`netsh int ipv4 set dynamic tcp start=49152 num=16384`
`netsh int ipv6 set dynamic tcp start=49152 num=16384`
然后重启即可

---

Searched from Google, probably it's about Hyper-V
Hyper-V will select ports from the TCP dynamic port range to reserve randomly
The solution is to narrow down the dynamic port range, run the following command with administrator privileges: 
`netsh int ipv4 set dynamic tcp start=49152 num=16384`
`netsh int ipv6 set dynamic tcp start=49152 num=16384`
Then reboot
