### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Shing1108** [LingFeng-bbben/MajdataView#108]
![螢幕擷取畫面 2023-06-03 180128](https://github.com/LingFeng-bbben/MajdataView/assets/107206176/519994f9-9abe-4733-a21f-07ce88edd268)
So I'm using Mac(Bootcamp) to open Majdata, and it pop out this.
Is there anyway can solve it?

**Comment by ATTVEonYouTube** [comment]
i have the sddame problem
