### ISSUE TITLE
使用Discord里找的粉色星星Skin的情况下，粉星星依然会携带一条蓝色弧线，而正确的现象应该是粉色弧线

### ISSUE THREAD

**Issue by Lapin237** [LingFeng-bbben/MajdataView#111]
## Where?

MajdataView

## New Feature Request

把星星换成粉色之后，依然带蓝色弧线出来，这不对。我认为可以把各种弧线的资源也放到Skin里。

**Comment by zhugezy** [comment]
《舞萌DX 2023》中，粉色星星头设置下携带的弧线依然为蓝色弧线。您是否可以提供更加详细的依据或说明文档？
