### ISSUE TITLE
majdataedit使用报错

### ISSUE THREAD

**Issue by FancyGemini** [LingFeng-bbben/MajdataView#119]
当使用majdataedit新建新工程或者打开任何已有工程均会出现以下报错，系统为Win11，更新系统小版本打Windows更新补丁亦无法解决。
![Image_1697791614146](https://github.com/LingFeng-bbben/MajdataView/assets/33599947/f0f395cd-b399-4f6e-aa8d-79a33682d081)
但是拿我的另一台Win11笔记本电脑majdata就可正常使用，并且弹出报错电脑的.net是完整的，在前一天晚上还能正常使用，但到第二天再开启谱面文件才发生的报错，期间没有删除卸载过任何电脑文件。
请问有无方法可以解决该报错问题？

**Comment by Moying-moe** [comment]
抱歉才回复，我今天定位了一个相同报错。你试试看关闭majdata，把谱面文件夹下的`majSetting.json`文件删除，然后再打开试试看？
