### ISSUE TITLE
在歌曲中间播放时谱面产生较大延迟

### ISSUE THREAD

**Issue by axpetis** [LingFeng-bbben/MajdataView#121]
## 问题出现的位置

在edit播放音频时

## 问题描述

播放谱面时，如果从头播放，那么已经写下的note能和歌曲对上，如果从中间开始播放，那么歌曲会比谱面早100~200ms播放

## 它是怎么出现的

如上

## 它可以复现吗

可以，在完整播放歌曲后（可能是预加载）依然有这个问题

## 可能有帮助的截图与文件
如图，在歌曲中间播放，当谱面走到图中的位置时，标红圈的音已经播放完了
![QQ截图20231125095355](https://github.com/LingFeng-bbben/MajdataView/assets/45459381/6275ab49-612f-4fe6-b742-0c64015f0088)
设备配置：联想y7000p 2022,i7-12700K,3050ti laptop

**Comment by axpetis** [comment]
版本是4.2.1

**Comment by LeZi9916** [comment]
@axpetis 检查一下track.mp3文件的码率是不是标准码率

**Comment by axpetis** [comment]
破案了，MP3不知道咋的转出来个148kbps

**Comment by KUR0FL4M3** [comment]
谢谢，困扰了我三个多小时的问题解决了
