### ISSUE TITLE
Hold与Break闪烁样式不正确

### ISSUE THREAD

**Issue by Moying-moe** [LingFeng-bbben/MajdataView#132]
## 问题出现的位置

MajdataView

## 问题描述

当前版本Hold与Break闪烁特效与官方效果不一致。

## 它是怎么出现的

Hold与Break（Break, Break hold, Break slide）

**Comment by Moying-moe** [comment]
很显然，官方的闪烁特效是通过调整`XXXXX_Eff_xx`的Sprite的透明度来实现的，但是我尝试了很多种方法，都和实际的效果有很大的差异。目前初步怀疑可能是因为用了一些Shader。

如果有任何人有头绪请联系我。

**Comment by LeZi9916** [comment]
> 很显然，官方的闪烁特效是通过调整`XXXXX_Eff_xx`的Sprite的透明度来实现的，但是我尝试了很多种方法，都和实际的效果有很大的差异。目前初步怀疑可能是因为用了一些Shader。
> 
> 如果有任何人有头绪请联系我。

官方的闪烁特效是通过更改贴图+循环修改亮度实现的，Hold有两个贴图：
- Hold
- Hold_On

**Comment by LingFeng-bbben** [comment]
fixed
