### ISSUE TITLE
MajdataEdit无响应

### ISSUE THREAD

**Issue by RubikZero** [LingFeng-bbben/MajdataView#134]
## 问题出现的位置

开始播放谱面后，MajdataEdit无响应

## 问题描述

使用老家的旧电脑（联想Y510P，windows 8.1，Majdata版本V4.2.1）写谱，点击播放后一段时间（可能和谱面密度相关，高密度谱时间更短）后，MajdataEdit无法响应点击，MajdataView仍然正常播放。打开任务管理器，看到MajdataEdit没有被标注为（无响应）。谱面播放结束后大约5秒，MajdataEdit可恢复正常。

## 它是怎么出现的

打开任意谱面，点击播放，等待1至10秒，MajdataEdit无响应，时间轴也不移动。部分谱面在无响应之前，先出现时间轴卡顿。部分谱面无响应后等待一段时间，MajdataEdit重新变成可以响应。但如果不停止播放谱面，仍然会再次无响应。

## 它可以复现吗

每次播放谱面都可以复现。重新启动Majdata或重新启动计算机，该问题仍然存在。
经测试，使用Majdata2.4.1版本、3.0版本、4.0版本、4.1版本，没有出现该问题。使用4.2版本和4.2.1版本可复现问题。

## 可能有帮助的截图与文件

无。打开任意谱面都出现该问题。

**Comment by Lynx-Rynn** [comment]
我家电脑开省电模式也会这样hhh但是正常情况没问题，可能是电脑太旧了计算能力不够

**Comment by LingFeng-bbben** [comment]
should be fixed in 4.4.0
