### ISSUE TITLE
majdataedit未响应

### ISSUE THREAD

**Issue by guizhilo** [LingFeng-bbben/MajdataView#136]
(Tips: 你可以删除小括号中的内容，这些内容只是提醒你应该写什么的)

## 播放铺面时长时间未响应，然后弹窗让保持view开启，但事实上已经开启了

(请详细描述您遇到的问题，以及您认为正常情况应当是怎么样的)

## 它是怎么出现的
在公共网络区域突然出现
## 它可以复现吗
100%复现
![Screenshot 2024_2_24 17_37_02](https://github.com/LingFeng-bbben/MajdataView/assets/161120715/9c18ae72-f1dc-4c93-8f51-6ad020db8cb1)

## 可能有帮助的截图与文件

(请上传出现问题时的截图。如果可以的话，您最好将您的谱面打包上传)
![Screenshot 2024_2_24 17_37_02](https://github.com/LingFeng-bbben/MajdataView/assets/161120715/4c9b1b15-4178-48fa-86c7-0194da35f2b1)

**Comment by TinyblackQvQ** [comment]
应该是本地端口8013被其他程序占用了，试一下在公共网络状态下使用命令行工具，输入`netstat -ano | findstr :8013`查看端口被占用情况。
