### ISSUE TITLE
MajdataView无法正常预览谱面

### ISSUE THREAD

**Issue by FancyGemini** [LingFeng-bbben/MajdataView#145]
出问题的位置应该算是两者都有。

在我的台式（配置为i7-12700KF+4070Ti）上，想要进行写谱时的谱面预览（文本跟随复选框下方的播放按钮）时，View会出现“只播放音频2s左右→突然出现这2s内的所有note判定”的情况，如果点击暂停，音乐会暂停但是谱面仍会继续进行播放，如果在播放期间拖动谱面时间轴，音乐会暂停但是谱面仍会继续进行播放并且时间轴没有做出任何移动。

但是在我的笔记本电脑（配置大致是九代i7+1650）上，就能正常使用。

下面是一段上文描述的视频录像：

[2024-03-23 01-27-06~1.webm](https://github.com/LingFeng-bbben/MajdataView/assets/33599947/2f90d4f3-5b75-42b5-a4e5-e344477c42f2)

**Comment by LeZi9916** [comment]
> 出问题的位置应该算是两者都有。
> 
> 在我的台式（配置为i7-12700KF+4070Ti）上，想要进行写谱时的谱面预览（文本跟随复选框下方的播放按钮）时，View会出现“只播放音频2s左右→突然出现这2s内的所有note判定”的情况，如果点击暂停，音乐会暂停但是谱面仍会继续进行播放，如果在播放期间拖动谱面时间轴，音乐会暂停但是谱面仍会继续进行播放并且时间轴没有做出任何移动。
> 
> 但是在我的笔记本电脑（配置大致是九代i7+1650）上，就能正常使用。
> 
> 下面是一段上文描述的视频录像：
> 
> [2024-03-23 01-27-06~1.webm](https://github.com/LingFeng-bbben/MajdataView/assets/33599947/2f90d4f3-5b75-42b5-a4e5-e344477c42f2)
> 

笔记本是插着电吗？

**Comment by FancyGemini** [comment]
> > 出问题的位置应该算是两者都有。
> > 在我的台式（配置为i7-12700KF+4070Ti）上，想要进行写谱时的谱面预览（文本跟随复选框下方的播放按钮）时，View会出现“只播放音频2s左右→突然出现这2s内的所有note判定”的情况，如果点击暂停，音乐会暂停但是谱面仍会继续进行播放，如果在播放期间拖动谱面时间轴，音乐会暂停但是谱面仍会继续进行播放并且时间轴没有做出任何移动。
> > 但是在我的笔记本电脑（配置大致是九代i7+1650）上，就能正常使用。
> > 下面是一段上文描述的视频录像：
> > 
> >   
> >     
> >     
> > 
> >     2024-03-23.01-27-06.1.webm
> 
> 笔记本是插着电吗？

插不插电都能正常使用，但是出问题的是台式，视频所录制的也是台式使用时候的画面

**Comment by LeZi9916** [comment]
> > > 出问题的位置应该算是两者都有。
> > > 在我的台式（配置为i7-12700KF+4070Ti）上，想要进行写谱时的谱面预览（文本跟随复选框下方的播放按钮）时，View会出现“只播放音频2s左右→突然出现这2s内的所有note判定”的情况，如果点击暂停，音乐会暂停但是谱面仍会继续进行播放，如果在播放期间拖动谱面时间轴，音乐会暂停但是谱面仍会继续进行播放并且时间轴没有做出任何移动。
> > > 但是在我的笔记本电脑（配置大致是九代i7+1650）上，就能正常使用。
> > > 下面是一段上文描述的视频录像：
> > > 
> > >   
> > >     
> > >     
> > > 
> > >     2024-03-23.01-27-06.1.webm
> > 
> > 笔记本是插着电吗？
> 
> 插不插电都能正常使用，但是出问题的是台式，视频所录制的也是台式使用时候的画面

看上去好像是View与Edit之间的Http通信堵塞造成的（？

**Comment by RiHisa** [comment]
这是4.3.1上的不知名BUG，我的电脑上运行4.3.1也是如此，但换成4.2.1（上一版本）是正常的，在这个问题被修复前建议先使用4.2.1版本

**Comment by LingFeng-bbben** [comment]
should be fixed in v4.4.0
