### ISSUE TITLE
用@表示宴谱中的圆形星星头（如1@-5[4:1],）

### ISSUE THREAD

**Issue by Eternal973** [LingFeng-bbben/MajdataView#153]
> ここに定義している記法は、MURASAKiで搭載された宴譜面など、特殊な譜面を記述する際の手助けとなりえる記法です。
> 通常TAPを星形TAPに変更する
> 1番TAPは【1,】と記述しますが、「$」を加えて【1$,】と記述すると、SLIDEを記述した際に現れる星形TAPに変化します。
> BREAK TAPやEX-TAPと併用することもできます。
> 「$」、「b」、「x」が2文字以上併記される場合、どのような順番で書いても構いません。
> また、「$」を2つ重ねて「$$」にすると、その星形TAPが回転するようになります。
> この時の星形TAPの回転速度は一定の速度になります。
> **星形TAPを通常TAPに変更する**
>【1-5[8:1],】のようにSLIDEを記述した場合、1番TAPは自動的に星形TAPに置き換わりますが、
>「@」を使って【1@-5[8:1],】のように記述すると、この星形TAPが通常TAPに変化します。
>SLIDEは通常通り処理されるため、通常TAPからSLIDEの矢印が伸びるという図になります。
>こちらもBREAK TAPやEX-TAPと併用することもできます。
>「@」、「b」、「x」が2文字以上併記される場合、どのような順番で書いても構いません。

参考simaiwiki写的星星头不能直接读
该写法（1@-5[4:1],）应与1/1?-5[4:1],效果相同

**Comment by LingFeng-bbben** [comment]
因为实际为冗余的写法 所以就不实现了
