### ISSUE TITLE
语法检查对于绝赞星星的问题

### ISSUE THREAD

**Issue by FlareAP** [LingFeng-bbben/MajdataView#174]
## 问题出现的位置

MajdataEdit (4.4.0 release)

## 问题描述

诸如{8}1-5b[8:1]的星星在语法检查中解析失败（View中正常）

（我刚刚接触simai语法，请原谅不准确之处）

具体来说，目前发现这种情况的星星均为绝赞星星，大部分为到对侧按键（1w5b, 3z7b, 4-6b[8:1]<8[16:1]），也有转一圈到相邻按键的（1>8b），且大部分为{8} [8:n]，{16} [8:n]，{8} [4:n]等（n为数字）

## 它是怎么出现的

我想录制一些fes+的谱面预览视频，于是下载了majdata。然后就发现了这个问题。

## 它可以复现吗

在我本地打开大部分fes+谱面均有该问题，可以复现。

## 可能有帮助的截图与文件

(请上传出现问题时的截图。如果可以的话，您最好将您的谱面打包上传)
大家应该都有这些谱吧（）

**Comment by YTSakura233** [comment]
编辑器暂时不支持新配置的检测，但是可以正常播放。

**Comment by XajilX** [comment]
按照simai wiki的说法，正确的写法应该是1-5[8:1]b，并且这样写语法检查不会报错

[Notations of Simai](https://w.atwiki.jp/simai/pages/1003.html)

原文中写的是 'To change the track of a SLIDE into a BREAK SLIDE, add a "b" **after the "]"** like 【1-4[8:3]b,】.'
