### ISSUE TITLE
添加直接导出视频的功能

### ISSUE THREAD

**Issue by Fros1er** [LingFeng-bbben/MajdataView#20]
（虽然我本人不写谱但看到批站上预览一堆水印有点难受。。
打算交个pr，但开始鸽之前不知道有没有这个需求。。

**Comment by tanetyan** [comment]
预览模式完直接出视频挺好的。

**Comment by LingFeng-bbben** [comment]
**支持**
实现这个功能你需要：
- View端将unity的渲染结果编码为视频
  - 这其中那个背景视频插件可能会很不友好 
- Edit端用bass.net库将各个通道的音频合成(有点麻烦)
- 调用ffmepg(?)合二为一

因为太麻烦了所以之前我根本不想写 笑死
有问题或者看不懂屎山可以发邮件或者QQ

**Comment by LingFeng-bbben** [comment]
哦对 这两个端是两个repo，恳请注意

**Comment by Fros1er** [comment]
> **支持** 实现这个功能你需要：
> 
> * View端将unity的渲染结果编码为视频
>   
>   * 这其中那个背景视频插件可能会很不友好
> * Edit端用bass.net库将各个通道的音频合成(有点麻烦)
> * 调用ffmepg(?)合二为一
> 
> 因为太麻烦了所以之前我根本不想写 笑死 有问题或者看不懂屎山可以发邮件或者QQ

好 谢谢(
不过我也不知道能不能鸽出来orz

**Comment by Fros1er** [comment]
有个问题...ffmpeg相关的库好像需要>win8.1，咱有没有win7用户...

**Comment by Fros1er** [comment]
鸽了，对不起...
