### ISSUE TITLE
编辑tab下的功能希望能全部加入快捷键设定

### ISSUE THREAD

**Issue by tanetyan** [LingFeng-bbben/MajdataView#21]
主要是想要镜像功能的快捷键

**Comment by LingFeng-bbben** [comment]
是要快捷键的设定还是要镜像的快捷键
如果你想改快捷键的话就直接改EditorSetting.json即可 就在根目录

**Comment by tanetyan** [comment]
加镜像的快捷键。
以后编辑类要加什么功能也希望都能快捷键。
