### ISSUE TITLE
請問有考慮做MacOS的版本嗎

### ISSUE THREAD

**Issue by ptchen314** [LingFeng-bbben/MajdataView#24]
我是死蘋果用戶
我想寫譜

**Comment by LingFeng-bbben** [comment]
.net framwork现在是只能在windows上跑哦，就算迁移到.net core好像也不太与wpf兼容的样子。unity那边倒是没问题。
- 而且没有苹果的测试环境
- 但是你可以装个虚拟机啦

**Comment by jing-shiun** [comment]
蘋果M1用戶沒人權啊這

**Comment by Moying-moe** [comment]
如果只是想播放谱面的话，我有空可以写个小工具，让View可以自己播放谱面（因为理论上来说MajdataEdit和MajdataView是两个独立的软件，它们之间是用内网通讯的）

**Comment by KankaiChan** [comment]
下个parallelsDesktop m1也能跑哇

**Comment by chenme21** [comment]
> 下个parallelsDesktop m1也能跑哇

跑是可以跑
但會卡

**Comment by Windoooors** [comment]
注意到 Majdata Edit 用 HTTP 来与 Unity 通信
是否有可能开放端口 让同一局域网里的 Windows PC 运行 Majdata Edit 并用 Mac 运行 Majdata View？
如果只有一台 Mac 的话可以用虚拟机运行 Edit ，在宿主机上运行 View

**Comment by LingFeng-bbben** [comment]
可以但是为啥
目前有一些把edit的功能移动到view的想法 待细致讨论
如果做出来的话就可以直接跨平台了

**Comment by Windoooors** [comment]
虚拟机跑 View 卡啊（x

**Comment by LingFeng-bbben** [comment]
see #146
