### ISSUE TITLE
3.0版本PresentationCore报错后吃谱。

### ISSUE THREAD

**Issue by kaguyas** [LingFeng-bbben/MajdataView#26]
由于是偶然出现所以没有保留错误信息。谱面文件没有发生变化，但majdata内怎么编辑都只会剩余2/3的谱，或者完全没有谱面。强制软件渲染对这个问题无作用。测试后相同谱面文件下 旧版本majdata没有这个问题。

**Comment by Moying-moe** [comment]
吞谱我也遇到过一次，但是因为触发条件太过苛刻所以目前为止暂时无法定位。

考虑的解决方案是加入一套更可靠的备份机制（类似于Microsoft Office的备份机制）
