### ISSUE TITLE
[Bug] Music-playing process wouldn't stop on specific behaviours

### ISSUE THREAD

**Issue by zhugezy** [LingFeng-bbben/MajdataView#3]
In MajdataEdit.exe, opening another maidata.txt in exchange of current maidata.txt when the current one is getting played would cause some troubles. For example,
step 1: start MajdataEdit.exe and open a maidata project;
step 2: click the "play" button;
step 3: open another maidata project(could be the current one again, or some project else) without clicking the "stop" button.
The music is expected to stop, but it isn't stopped.

**Comment by LingFeng-bbben** [comment]
Fixed in Alpha4.1
