### ISSUE TITLE
Hold在按住的情况下会发光

### ISSUE THREAD

**Issue by Moying-moe** [LingFeng-bbben/MajdataView#37]
不清楚是dx后加入的还是一直有的，反正Hold被按住时，其外观会发生改变。

**Comment by SpadeLushen** [comment]
旧框也有，但不像dx这么明显

**Comment by Moying-moe** [comment]
忘了关了，Fixed in 80f8e271389bb6b19f60a35a8f7d15ae5cdde4c2
