### ISSUE TITLE
hanabi特效叠加问题

### ISSUE THREAD

**Issue by Moying-moe** [LingFeng-bbben/MajdataView#39]
由于在MajdataView中，每个包含hanabi特效的touch（或touchHold）对象都会携带hanabi特效对象，因此，当有多个hanabi相互叠加时，hanabi特效会彼此叠加。但正确的状态应当是，每次hanabi特效被触发时，上一个hanabi特效会被关闭。

即，hanabi特效应当如同`TapEffect`一样运作。

**Comment by Moying-moe** [comment]
参考：[【maimai】World's end loneliness 最速理論値AP!!!! (Player:よしき)](https://www.bilibili.com/video/BV1914y1t7E9?t=153.3)

**Comment by LingFeng-bbben** [comment]
已修
