### ISSUE TITLE
開頭以及結束動畫

### ISSUE THREAD

**Issue by Falldielove** [LingFeng-bbben/MajdataView#41]
開頭動畫和結束動畫可以更改嗎
以及開頭的BPM節奏四聲是否能先讓音樂暫停
等BPM節奏撥放完畢再開始音樂

**Comment by Moying-moe** [comment]
根据我们对官方游戏的观察，似乎在官方游戏中，这四声BPM提示就是占用游戏时间的。

关于为何要这么做，主要是因为BPM提示音播放逻辑的问题。实际上，现在的做法是在整个谱面的开头添加4个虚拟的“BPM提示音NoteSE”来实现的，他就像一个正常的Tap的音效一样被播放。

因此，目前来说，这可能不会被修复，因为这需要重写音频逻辑。目前你可以使用Adobe Audition为音乐前面添加上一段静音音频的方式来解决这个问题，你可以使用AU的BPM器来对齐音频，或者直接手动添加静音片段，时间长度的计算公式为`240/BPM`秒。当然，这也许会在未来得到优化。

关于开头动画和结束动画，这些似乎是写死的东西，因为不是我做的所以我不清楚客制化的难度有多大。
