### ISSUE TITLE
Translation/Localization required!

### ISSUE THREAD

**Issue by Moying-moe** [LingFeng-bbben/MajdataView#42]
More texts were added to Majdata, so we need translation help!

Japanese localization is the **most complex part** because **most of our collaborators are not proficient in Japanese**.  So there are plenty of texts need to be translated into Japanese.

Also, some English texts **may not in the most accurate translation**, so you can give some advice about it.

**If you understand English, then you can give some help**. The texts were translated into English so that you can understand what these texts means. **Even if you don't know how to use Github, it doesn't matter**. You can just type texts in this issue and metion me (@Moying-moe ), and I will help you.

## If you know how to use Github...

These texts are in [MajdataEdit](https://github.com/LingFeng-bbben/MajdataEdit/), **which is not this repository!**

If you have *Visual Studio* in your computer, you can Fork **MajdataEdit**, edit localization files, commit and start a **pull request**. We will see your **PR** and merge it. The localization files are in `./Langs/` folder, file names are `Langs.en-US.resx` and `Langs.ja.resx`.

The texts need to be translated or checked have `<comment>` tag on it. It may be "Maybe not the most accurate translation" or "Translation required".

The texts may have symbols like `{1}`, `{0}`. It will replaced into actual content while the software running. And you need to place it in your text properly.

One example:

Raw text: `[SyntaxError] "{0}"({1}L,{2}C) fail to analyze，may be a syntax error here.`

It will look like `[SyntaxError] "1-b5[8:1]"(5L,1C) fail to analyze，may be a syntax error here.` which shown to users.

## If you does not know how to use Github...

You can just download and edit [MajdataEdit/Langs.ja.resx](https://github.com/LingFeng-bbben/MajdataEdit/blob/master/Langs/Langs.ja.resx) (which is **Japanese** localization resources file) and [MajdataEdit/Langs.en-US.resx](https://github.com/LingFeng-bbben/MajdataEdit/blob/master/Langs/Langs.en-US.resx) (which is **English** localization resources file). 

If you does not know about xml file format, it doesn't matter. I will summarize a text table in next few days. You can just copy that table, replace the texts need to be translated. Then send it under this issue and mention me (@Moying-moe ).

---

And, thanks a lot for all contributors.

**Comment by Moying-moe** [comment]
当然如果有会中文和日语的大手子能帮忙就更好了。

**Comment by N-Tohmi-7417** [comment]
Hello, Moying-moe-san.
I'm Japanese people and I want to help these translate to Japanese language.

I confirmed a content about MajdataEdit/Langs.ja.resx. It has some revision points.
Could you wait for next Monday? I'll write a comment with attach Langs.ja.resx.

**Comment by Moying-moe** [comment]
> Hello, Moying-moe-san. I'm Japanese people and I want to help these translate to Japanese language.
> 
> I confirmed a content about MajdataEdit/Langs.ja.resx. It has some revision points. Could you wait for next Monday? I'll write a comment with attach Langs.ja.resx.

ofcourse! thanks a lot.

**Comment by N-Tohmi-7417** [comment]
Moying-moe-san, thank you for waiting.
I translated content of Langs.ja.resx to Japanese language.
The content was designed with the kind of message used in Japanese computers in mind.
If you can, translate these Japanese language into Chinese language or English to see if there is any discrepancy.

But I couldn't understand only one sentence...
What is the feature of "ChartRefreshDelay"?
I couldn't figure it out, so I wrote temporary "？？？" there.
I'll write the sentence of Japanese language when you give me a meaning of feature. (may be tonight)

And I think the text of the error message when there is TOUCHs in the chart should be
"TOUCH and TOUCH HOLD are not supported" (English) and
"TOUCH・TOUCH HOLDには対応していません" (Japanese).
[Langs.ja(220829edited).zip](https://github.com/LingFeng-bbben/MajdataView/files/9441016/Langs.ja.220829edited.zip)

**Comment by Moying-moe** [comment]
> Moying-moe-san, thank you for waiting. I translated content of Langs.ja.resx to Japanese language. The content was designed with the kind of message used in Japanese computers in mind. If you can, translate these Japanese language into Chinese language or English to see if there is any discrepancy.
> 
> But I couldn't understand only one sentence... What is the feature of "ChartRefreshDelay"? I couldn't figure it out, so I wrote temporary "？？？" there. I'll write the sentence of Japanese language when you give me a meaning of feature. (may be tonight)
> 
> And I think the text of the error message when there is TOUCHs in the chart should be "TOUCH and TOUCH HOLD are not supported" (English) and "TOUCH・TOUCH HOLDには対応していません" (Japanese). [Langs.ja(220829edited).zip](https://github.com/LingFeng-bbben/MajdataView/files/9441016/Langs.ja.220829edited.zip)

Thanks for your help! I'm sorry for reply on you after 11 days, I'm quite busy these days. Your translation will merge into the program in few days.

And, about "ChartRefreshDelay". When user is editing his chart, **MajdataEdit** will analyze his chart content so that Majdata can generate timeline preview (*at the bottom of MajdataEdit windows*) and json file for MajdataView to play the chart. But this operation use a lot of memory and CPU. So we add delay on it.

When you are typing in the textbox, Majdata will not analyze your chart until you stop typing. So, "ChartRefreshDelay" detemined the time that Majdata wait user typing.

For example: Chart Refresh Delay is set to 1000ms. Now, user keep typing. And then, he stop typing. After 1 second (which is 1000ms), timeline preview will refresh and user can see new notes on it which he typed.

I hope you can understand the meaning of "ChartRefreshDelay" depend on the content above. And once again, **Thank you very much for your contribution.**

**Comment by N-Tohmi-7417** [comment]
Moying-Moe-san, don't worry! No problem.

Thank you for clearly description.
Then, I think that this sentence should be name "譜面プレビュー反映猶予(単位:ミリ秒)".
If there has lettering space, please add "この数字が小さいほどエディタ下部のプレビューが早く更新されますが、動作が重くなる可能性があります".

I hope i can be of any help to you.

**Comment by Moying-moe** [comment]
> Moying-Moe-san, don't worry! No problem.
> 
> Thank you for clearly description. Then, I think that this sentence should be name "譜面プレビュー反映猶予(単位:ミリ秒)". If there has lettering space, please add "この数字が小さいほどエディタ下部のプレビューが早く更新されますが、動作が重くなる可能性があります".
> 
> I hope i can be of any help to you.

OK, I'll handle this soon. Thanks!
