### ISSUE TITLE
exnote顯示問題

### ISSUE THREAD

**Issue by Falldielove** [LingFeng-bbben/MajdataView#43]
![image](https://user-images.githubusercontent.com/95141504/186569652-63cb4739-989d-4c77-b5ec-8099906737fb.png)
更新之後 exnote變得很怪
![image](https://user-images.githubusercontent.com/95141504/186569952-ef7b6876-6ee7-4ba7-af4c-5c2aab2a9bcf.png)

**Comment by Moying-moe** [comment]
具体怎么怪了，没看出来。我觉得应该是skin的问题。

**Comment by Moying-moe** [comment]
这可能是一个旧版本的BUG，请更新到最新快照版。如果还有问题，请重新发一个issue并进一步详细描述。
