### ISSUE TITLE
关于新要素，New notes in the festival version.

### ISSUE THREAD

**Issue by LingFeng-bbben** [LingFeng-bbben/MajdataView#44]
1.  星星拼接：要写新语法和新的尾判条
2.  hold BREAK, slide BREAK, EX BREAK等：修改edit的音效播放逻辑，view新增素材和皮肤
3.  TOUCH：A、D区touch验证。烟花多种位置

**Comment by LingFeng-bbben** [comment]
3 finished in 058ea77

**Comment by Moying-moe** [comment]
# Festival新要素术语和语法备忘录

## 组合Slide

Festival中新出现的，将多个Slide首尾相接组合的Slide，称作组合Slide。

组合Slide中被组合的Slide数量不作硬性限制。

组合Slide只有一个星星头、一个启动音效、一个尾部判定条。

### 语法

将多个Slide首尾相接的写在一起，并将时长写在最后。

如：1v3和3-5的组合，应当写成`1v3-5[4:1]`。

如果需要对星星头进行修饰，如绝赞星星头或ex星星头，则应当写在第一个数字的后面，如`1bv3-5[4:1]`。

## 新种类的Break

共有三种，Break Hold、Break Slide与Ex Break。

### Break Hold

当Break开头时，播放判定音、正解音以及欢呼声。

当Break结束时，应当播放**五角星的tap特效**（而非六边形）

#### 语法

类似于Ex Hold的写法，可以将b写在h符号前或后，但是必须写在hold时长前。如：`1hb[4:1]`、`2bh`

### Break Slide

当Slide被完成时，播放欢呼声。

#### 语法

书写在所有数字的最后，时长之前。如：`2^7b[8:1]`。

如果星星头和Slide本体都需要Break，那么都要书写，如`2b^7b[8:1]`

### Ex Break

触发时，播放判定音、正解音和欢呼声。

是否还需要播放ex音效暂时不清楚，有待验证。

#### 语法

既可以先书写ex再书写break，也可以反过来。如：`1bx`、`2bx-5[8:1]`。

## Touch

Touch可以在A和D区出现（过去版本已实现）

Hanabi可在任意区域出现。

### 语法

略

**Comment by Moying-moe** [comment]
# 新版本的资源文件变动（暂定）

## Skin

新增：

- `slide_break.png`，为Break Slide的滑轨资源图片
- `hold_break.png`，为Break Hold的资源图片

## SFX

变动：

- `tap.wav`更名为`answer.wav`（规范化变动）
- `ex.wav`更名为`judge_ex.wav`（规范化变动）
- `break.wav`的两个音效，即Break的判定音和理论值音（欢呼音）被分割为`judge_break.wav`和`break.wav`两个文件

新增：

- `judge.wav`，为普通Note在获得Perfect判定时播放的音效，比如，普通Tap、普通Hold的开头与结尾会播放。

**Comment by Moying-moe** [comment]
2 finished in d77b034781cb2828e95378816e07fb7cab17f374

**Comment by Moying-moe** [comment]
3 finished in 04a39f5b48192dd2af8ec6dd70d8a64397a4b8c4

**Comment by Moying-moe** [comment]
Ling桑，我滴任务，完成辣，哈哈哈哈 @LingFeng-bbben

**Comment by LingFeng-bbben** [comment]
3qxx
