### ISSUE TITLE
新一代maimai でらっくす更新

### ISSUE THREAD

**Issue by Falldielove** [LingFeng-bbben/MajdataView#45]
新一代「maimai でらっくす FESTiVAL」
更新的鍵位，大概如下
1.第一點更新
Break Update (加分鍵更新) : 
Hold鍵、Slide鍵(滑條不含星星)、EX鍵
這些鍵位增加BK鍵 材質如圖(一)
![image](https://user-images.githubusercontent.com/95141504/190144579-3b3e002a-f0ed-48d6-832b-6b6896b29c6b.png)
2.第二點更新
滑星種類變多，公式變更複雜
樣式如下圖(二)
![image](https://user-images.githubusercontent.com/95141504/190146320-404cf357-0dea-46d7-881b-62cee74207f0.png)
大概樣子就是把原本需要好幾顆滑星的鍵位
變成只需要一顆就可以變換好幾位的滑星
3.需加強部分:
上一次我有提到的 EX材質問題
當材質包在使用粉色滑星的時候
EX顏色還是會顯示藍色的，且EX的白框不像原版那樣對齊
似乎是沒有挑整好材質導致?
建議:
希望加入更多樣式的Skin，有些影片裡介紹的樣式很多在連結裡都沒有'
希望中間的數字顯示不只有Combo可以增加0-100% And 101%的樣式顯示
以上就是這些，本人不太會寫程式，但很喜歡使用你們的制譜軟體
我想讓這個做譜環境變得更完美，謝謝製作團隊!
希望可以盡快更新!!!
參考影片:「https://www.youtube.com/watch?v=CjxfF7IB9gk&t=195s」

**Comment by LingFeng-bbben** [comment]
以上收到
其他的：
想要更多的skin的话其实改图片就可以自制
0-100这样的中心显示因为其实全是autoplay所以我觉得没啥必要，而且旁边的信息栏里面已经有了

**Comment by Moying-moe** [comment]
已完成。其他细节方面提升如果还需要的话，请再发一个issue
