### ISSUE TITLE
view显示问题

### ISSUE THREAD

**Issue by lianxinyuan01** [LingFeng-bbben/MajdataView#47]
![C)5@0W%QEKP5FK5U5F2BABI](https://user-images.githubusercontent.com/113598473/190385008-870bbe0b-563c-4e68-bd82-56500c26d1eb.png)
大概是在写完按保存的快捷键后拖动了条，然后整个view就亮度拉满了，铺面原背景也没显示，更改了亮度也没有反应，重新打开铺面也是一样，然后就是录制模式打开没有了显示铺面封面的动画，但铺面tap出来是正常的，重启软件也是一直是这样

**Comment by Moying-moe** [comment]
已在v4.0-SNAPSHOT.2修复，原因是我之前测试的时候把try catch给注释掉，后来忘记改回去了。大概率是因为你谱面有语法错误。

请更新到快照2版本，如果仍然出现此问题，请将谱面文件夹内所有文件打包上传。

如果没有问题也请回复一下

**Comment by lianxinyuan01** [comment]
> 已在v4.0-SNAPSHOT.2修复，原因是我之前测试的时候把try catch给注释掉，后来忘记改回去了。大概率是因为你谱面有语法错误。
> 
> 请更新到快照2版本，如果仍然出现此问题，请将谱面文件夹内所有文件打包上传。
> 
> 如果没有问题也请回复一下

更新后就提示是语法错了，现在没有问题了

**Comment by Moying-moe** [comment]
OK
