### ISSUE TITLE
从谱面中途开始发到查看器播放，会出现异常，但还能正常播放

### ISSUE THREAD

**Issue by SpadeLushen** [LingFeng-bbben/MajdataView#5]
https://homepc.imlushen.com:20620/public/MajDataView_error_logs/202107231941/Player.log

**Comment by LingFeng-bbben** [comment]
修复计划
1. 阻止播放开始时间前的note生成
2. slide在过渡时段后设置alpla值为1

**Comment by LingFeng-bbben** [comment]
修了
