### ISSUE TITLE
pv无法显示

### ISSUE THREAD

**Issue by Yeux-7** [LingFeng-bbben/MajdataView#50]
[DIVE with Ü.zip](https://github.com/LingFeng-bbben/MajdataView/files/9585586/DIVE.with.U.zip)

**Comment by Moying-moe** [comment]
待会看

**Comment by Moying-moe** [comment]
你好，你发的文件里bg.mp4就是一张静态图片的视频。你所说的PV无法显示，是指什么？是播放后黑屏吗？

我没能复现。尝试更新到v4.0快照3试试看
