### ISSUE TITLE
BK hold問題

### ISSUE THREAD

**Issue by Falldielove** [LingFeng-bbben/MajdataView#52]
BK hold問題
BK Hold不會被統計進Hold裡

**Comment by tutuw002** [comment]
遊戲中break hold/break slide也是視作break，不會視作hold/slide

**Comment by Moying-moe** [comment]
根据日本友人反馈，FESTiVAL版本中所有的Break衍生种均会被计入Break数量，而不是其原本的类型。包括Break Tap、Break Hold、Break Slide
