### ISSUE TITLE
Festival的连续Slide仍会检测长度为1并报错

### ISSUE THREAD

**Issue by RubikZero** [LingFeng-bbben/MajdataView#53]
Festival的连续Slide中，如果有长度为1的子Slide，会引起报错。我认为连续Slide中大多数时候没有必要因为长度为1报错，除非是1-2-1[4:1]这样的特殊情况。

**Comment by Moying-moe** [comment]
原版好像没有一格直线吧……festival解禁的是一格弧线1^2

**Comment by Moying-moe** [comment]
嘶，也有人说有。不过目前项目中没有一格直线Slide的Prefab，所以暂时没法做。搁置
