### ISSUE TITLE
希望编辑器增加拍号设置功能

### ISSUE THREAD

**Issue by RubikZero** [LingFeng-bbben/MajdataView#54]
能否增加一个拍号设置，比如设置成3/8拍子，开头就只会响三声，间隔是八分音符，并且时间轴也会把三个八分音符当做一小节，星星的启动时间也设置为八分音符。
如果改提示音间隔和星星启动时间比较麻烦，希望开头提示的次数和时间轴上每小节的拍数可以更改。

**Comment by Moying-moe** [comment]
`&clock_count=3`即可让开头响三声。

间隔8分以及时间轴小节线，需要等FESTiVAL所有新功能稳定以后再写。

**Comment by Moying-moe** [comment]
merged into #58
