### ISSUE TITLE
4.0 snapshot的hold會全部被算進Break裡面

### ISSUE THREAD

**Issue by darkness741852** [LingFeng-bbben/MajdataView#55]

**Comment by darkness741852** [comment]
![image](https://user-images.githubusercontent.com/113963637/191170204-7443694c-c5e4-418c-bbd9-0cbdf3587a96.png)

**Comment by Moying-moe** [comment]
莫慌，待会看看

**Comment by Moying-moe** [comment]
算在Break里是正确的情况，不过Break的总数好像有点问题

**Comment by Moying-moe** [comment]
你能不能确认一下你使用的是哪一个版本的快照？我这里在v4.0-SNAPSHOT.2下无法复现

**Comment by darkness741852** [comment]
等等 應該是我的問題 我還在無印SNAPSHOT
