### ISSUE TITLE
Support the notation grammar for the official Simai Release

### ISSUE THREAD

**Issue by LingFeng-bbben** [LingFeng-bbben/MajdataView#62]
## Where?

(MajdataEdit)

## New Feature Request
See [link](https://twitter.com/formiku39854/status/1572593131186692096?s=20&t=BgMKFEG2fezKScoZLiWnsw)

- [x] Move the slide break 'b' to the end of []
- [x] Chain Slide with **different speed** as: 4qq4[a:b]z8[c:d]

**Comment by Moying-moe** [comment]
我认为break slide的b标记位置应该二者皆可，增加支持就行了，挪过去有些难受。
