### ISSUE TITLE
未将对象引用设置到对象的实例

### ISSUE THREAD

**Issue by 6phenylethane** [LingFeng-bbben/MajdataView#63]
## 可能有帮助的截图与文件

![`A}H5`Y@Q`N2R%ZAIGD~Q%C](https://user-images.githubusercontent.com/43375604/191905631-d1f83ab8-e1d1-4e93-acad-613f76d7bf86.png)

**Comment by Moying-moe** [comment]
首先，issue格式错了

其次，请给一下你的系统版本、majdata版本，然后上传谱面文件（以确保不是谱面文件的问题，即便大概率确实如此）

**Comment by miyazakiakino** [comment]
希望能给一个解决方案，不胜感激

**Comment by Moying-moe** [comment]
> 感觉写第二个谱子的时候都会出现这个问题……应该怎么解决比较好……

我需要更多信息，在我的电脑上无法复现这个问题，请提供你的majdata版本，电脑相关数据，稳定复现的步骤。以及这个问题是什么时候出现的（如：更新到XXX版本后出现该问题

**Comment by miyazakiakino** [comment]
majdata4.0 snapshot-3
电脑就是win10
[maidata.txt](https://github.com/LingFeng-bbben/MajdataView/files/9685264/maidata.txt)
就是说，把track文件一放进去就会出现这种问题……
或者写“maidata已存在”之后立马会出现这个问题。

**Comment by Moying-moe** [comment]
> majdata4.0 snapshot-3 电脑就是win10 [maidata.txt](https://github.com/LingFeng-bbben/MajdataView/files/9685264/maidata.txt) 就是说，把track文件一放进去就会出现这种问题…… 或者写“maidata已存在”之后立马会出现这个问题。

请详细复述复现过程。我猜测的复现过程如下：

- （前置）使用任意方式创建track.mp3的谱面文件
- 单击菜单中的文件->新建
- 找到第一步所述的track.mp3，打开，提示maidata已存在
- 出现截图中的报错

以上猜测是否有误，如果有误，请指出不一样的地方。比如，track.mp3是拖拽入窗口新建，而非用菜单栏。或比如，需要在已经打开目前的track.mp3时，直接尝试新建。

此外，以上问题，是仅在这样的情况下（即试图为已经有谱面的track.mp3创建谱面 提示“maidata已存在”时）才会出现，还是曾经在其他情况中，也出现过？

**Comment by miyazakiakino** [comment]
复现过程就是这样子的！
不只是maidata已存在的时候会报这个错，我把原来的maidata删掉了依然会出现这个问题……
自己去下歌改成track就不行，但是用官谱的文件却可以……

**Comment by miyazakiakino** [comment]
用官谱的谱面文件是可以正常打开的，但是用自己下的音乐就会报错

**Comment by Moying-moe** [comment]
> 用官谱的谱面文件是可以正常打开的，但是用自己下的音乐就会报错

把出错的谱面文件（包括track maidata 以及文件夹下的json文件）传上来……我没有直接获取你电脑里文件的超能力。

还有你的复现过程还是很模糊，你可以参考我上面写的复现步骤的格式来写。请一定要注意：在你面前的人，是隔着屏幕和网线的，对你电脑以及你的操作习惯、实际操作方式**毫不知情**，对于出错时间和方式**完全无法知晓**，对于几乎所有具体情况**完全不知道**的人，所以你需要**尽可能详细地复述**在出现问题的前后，你是如何操作的。

用比较形象生动的话来说，就是，**你要把开发者当傻子**。

换言之，你的描述，可以保证一个从未触发过此BUG的人，根据你的描述，可以一步一步地准确（即100%）还原你的操作过程，并触发这个BUG。

从另一方面来说，希望你能理解：**绝大部分未解决的issue**并非开发者无法修复这些问题，亦或是不想修复这些问题，**而是因为开发者无法复现这个问题，从而无法找到问题的根源，进而排查问题缘由并修复此问题**。因此，**绝大部分未解决的issue，都是因为复现条件没有被完美的陈述而导致的。**

期待你的回复

**Comment by miyazakiakino** [comment]
[maidata.txt](https://github.com/LingFeng-bbben/MajdataView/files/9696908/maidata.txt)

**Comment by miyazakiakino** [comment]
[snooze.zip](https://github.com/LingFeng-bbben/MajdataView/files/9696914/snooze.zip)

我从最最最起初开始说起吧。

->**没有官谱的曲子**，且是**maidata.txt文件被删除**的情况下
1. 音乐软件下好歌，更名成track.mp4（试了几个软件都能正常播放）
2. 打开majdata的edit，点新建
3. 把track文件选中之后，直接报错
4. 回去看文件夹里的文件，**出现了maidata.txt**（内容只有模板），**但是是无法正常打开的。**

->**没有官谱的曲子**，在**新建谱面的时候已经报错了**，**但是留下了maidata.txt**（内容只有模板）
1.打开majdata的edit，点打开，直接报错
或者，在已经有maidata.txt的情况下再重新新建一个相同歌曲的谱子，会写"maidata.txt已存在"，之后直接报错。
我记得之前情况还会出现时间出现乱码（比如时间变成1:*0那样的情况……）

报错之后留下的maidata.txt，里面的内容如下：
&title=请设置标题
&artist=请设置艺术家
&des=请设置做谱人
&first=0

如果按照官谱的谱面文件把之前的预备的代码全部都复制过去，有官谱的曲子运转都是正常的（但是连续弄两张谱子就会报错了……），没有官谱的曲子就是会直接报错的情况。

->**有官谱的谱子**，有谱子的情况下就只会说“maidata.txt已存在”，音乐是可以正常播放的，也不会有那一长串的报错问题……
并且选择难度，也都可以直接呈现出对应难度的谱子——
总而言之，有官谱的谱子都是可以正常播放的（除非说已经做了一张谱子，但是又连着再做一张那就会报错了）。
如果还有说的不完备的地方可以接着指出，我也会尽量说清楚的！
