### ISSUE TITLE
未将对象引用设置到对象的实例

### ISSUE THREAD

**Issue by miyazakiakino** [LingFeng-bbben/MajdataView#66]
如题………
第一次写谱的时候可以，第二次写谱的时候就完全不行了。

https://user-images.githubusercontent.com/114753088/193411530-1a77aac4-0294-4932-b88b-c1a65855835a.mp4

**Comment by Moying-moe** [comment]
可能找到了原因，但是不太确定。能不能加个联系方式，我需要测试一下

**Comment by Moying-moe** [comment]
修复已经推了，会放在下一个版本的更新里。你这个可能是因为没读写权限导致的。不要把majdata或者谱面放在一些容易出现权限问题的文件夹中，如User文件夹，系统盘等
