### ISSUE TITLE
星星头的音效没了

### ISSUE THREAD

**Issue by tanetyan** [LingFeng-bbben/MajdataView#67]
(Tips: 你可以删除小括号中的内容，这些内容只是提醒你应该写什么的)

## 问题出现的位置

(是MajdataEdit——也就是谱面编辑器——出现了问题，还是MajdataView出现了问题，亦或是二者都出现了问题呢？)

## 问题描述

(请详细描述您遇到的问题，以及您认为正常情况应当是怎么样的)

写了下述内容之后，星星头没有音效。
<img width="252" alt="image" src="https://user-images.githubusercontent.com/88204753/194937610-fb48fa1e-6225-48a4-b4bd-419cc5f3b323.png">

## 它是怎么出现的

(请详细描述出现问题前以及出现问题时，您正在做什么。如：我在Edit中写了`1-2-4[4:1]`，在我写完的一瞬间，Edit崩溃了)
(如果问题后来消失了，请描述在出现问题后你做了什么事情，包括重启。如果问题没有消失，也请您注明)

下载下述的两个版本进行播放

- Majdata_v4.0-SNAPSHOT.3
- Majdata_Beta3.1
 
补充：再次打开自己之前用的版本发现也没音效了。可能和开过Majdata_v4.0-SNAPSHOT.3版本有关。
自己是先开了v4.0-SNAPSHOT.3之后再开的Beta3.1

## 它可以复现吗

(如果您重复您之前的操作，这个问题再次出现了，那么说明它可以复现。否则，说明不可以。)

可以

## 可能有帮助的截图与文件

(请上传出现问题时的截图。如果可以的话，您最好将您的谱面打包上传)

**Comment by tanetyan** [comment]
发现是不知道怎么的把我音量变成0了。

**Comment by Moying-moe** [comment]
> 发现是不知道怎么的把我音量变成0了。

笑死我了。

因为之前的更新新增了判定音，所以打开旧的文件的时候，判定音就会变成0，不是你的锅。
