### ISSUE TITLE
无理检测无法正确判断类似Believe the Rainbow[Master]的Slide配置

### ISSUE THREAD

**Issue by RubikZero** [LingFeng-bbben/MajdataView#68]
## 问题出现的位置

无理检测无法正确判断类似Believe the Rainbow[Master]的Slide配置

## 问题描述

类似5<7[2:1]*<8[4:3]*<1[1:1]*<2[4:5]*<3[2:3]*<4[4:7]*<5[1:2]的配置，或反过来的不同起点相同终点同时判定的Slide会被判定为多押

**Comment by Moying-moe** [comment]
啊，贴边Slide太难判了，有空再写
