### ISSUE TITLE
音符延遲

### ISSUE THREAD

**Issue by Falldielove** [LingFeng-bbben/MajdataView#69]
(Tips: 你可以删除小括号中的内容，这些内容只是提醒你应该写什么的)

## 问题出现的位置

音樂在撥放會有延遲

## 问题描述

音樂在撥放時有時候會有延遲

## 它是怎么出现的

沒做甚麼，三不五時出現

## 它可以复现吗

可以

## 可能有帮助的截图与文件

有點難

**Comment by Moying-moe** [comment]
你想描述的是以下哪种：

- 音乐和音效之间存在延迟
- 音乐和谱面显示存在延迟
- 音效和谱面显示存在延迟

> 音乐：即歌曲
> 音效：即note的判定音等
> 谱面：即在MajdataView中显示的谱面预览画面

这样的延迟是什么样的程度呢？如：几十毫秒（只是听着觉得“歪了”）、几百毫秒（完全对不上）、几秒（肉眼可见的延迟）？

此外，请提供你的电脑配置。

---

一些可能有帮助的原因以及解决方案：

1. 检查你的时区是否为UTC+8。如果不是，有概率导致一些BUG
2. 目前Majdata的音/画方案是：View显示画面，Edit播放音频。而因为Edit的性能问题，当音效过多（Note过多），或电脑配置较低时，Edit可能会卡顿或卡死。而二者（View和Edit）之间，在开始播放后就不会进行同步，所以一旦二者中某一个卡顿，则会出现音画不同步的情况。解决方案是：换一台更高配的电脑
3. BGA或者一些音频，在首次播放的时候，可能需要一些时间加载，这可能会导致不同步。尝试在录制前先播放一遍，第二次播放时可能就会不卡顿。
4. 目前已知，Nvidia显卡的自带录制（Geforce Experience录制）会低概率的诱发音频和视频的卡顿，另外，Geforce Experience录制开始或结束的提示条在系统关闭全屏优化时会导致软件卡顿。可以尝试使用其他录制软件，或者多次录制。

总的来说，我认为这是一个性能问题。目前较为通用的解决方案就是使用更高配的电脑。或者检查你是否在使用集成显卡运行Majdata
