### ISSUE TITLE
歌曲时间长了以后，底下的时间轴条会变全黄，看不到写了什么

### ISSUE THREAD

**Issue by siqod** [LingFeng-bbben/MajdataView#70]
## 问题出现的位置

MajdataEdit

## 问题描述

底下不该变全黄啊，歌曲时间短一点不会出现这个问题，长了就不行了

## 它是怎么出现的

我只是在正常写谱子，拖动时间轴到2分45秒多接近2分46时，突然问题就来了，而且拖时间轴到3分钟也无法消除问题，重启Majdata甚至电脑都仍然这样，已确认音源为采样率44100Hz,码率128K。

## 它可以复现吗

测试3个谱子和曲子，均有此问题。可复现。

## 可能有帮助的截图与文件

![MajdataEdit(v4 0-SNAPSHOT 3) - 0verf1ow 2022_10_31 13_36_42](https://user-images.githubusercontent.com/117062074/198938950-391b26c9-4cba-45af-9e1c-35bdfb7f0a9d.png)
![MajdataEdit(v4 0-SNAPSHOT 3) - 0verf1ow 2022_10_31 13_38_45](https://user-images.githubusercontent.com/117062074/198939126-80e4c055-3ef7-4f7c-8b73-e99f26a1574e.png)
[3charts.zip](https://github.com/LingFeng-bbben/MajdataView/files/9898364/3charts.zip)
我把出这问题的谱子一起传上来了

**Comment by Moying-moe** [comment]
有空看看

**Comment by LingFeng-bbben** [comment]
这是因为歌曲过长导致生成的位图太长导致的
可以缩小下面的缩略图解决
