### ISSUE TITLE
软件报错打不开

### ISSUE THREAD

**Issue by MorningFur** [LingFeng-bbben/MajdataView#74]
显示这样，试了强制软件渲染也一样
![image](https://user-images.githubusercontent.com/109568172/199206995-c305a186-99f6-4446-bf83-339a33bac756.png)

**Comment by Moying-moe** [comment]
什么版本

**Comment by MorningFur** [comment]
> 什么版本

v4.0.0-rc

**Comment by Moying-moe** [comment]
比较难排查，因为看起来似乎是WPF的报错。

请提供信息帮助排查：

1. 是一直无法启动？还是使用以前的旧版本可以启动，更新到最新版以后不行了呢？如果曾经使用旧版本可以启动，但是在某个版本以后就无法启动了，请提供版本。
2. Majdata文件夹放在哪里？比如，是否放在了系统盘。
3. 请检查是否缺少了dll文件，或者没有安装.NET框架。因为这个报错看起来似乎是某些库加载失败了。
4. 使用的操作系统、操作系统位数以及CPU型号。

**Comment by MorningFur** [comment]
> 比较难排查，因为看起来似乎是WPF的报错。
> 
> 请提供信息帮助排查：
> 
> 1. 是一直无法启动？还是使用以前的旧版本可以启动，更新到最新版以后不行了呢？如果曾经使用旧版本可以启动，但是在某个版本以后就无法启动了，请提供版本。
> 2. Majdata文件夹放在哪里？比如，是否放在了系统盘。
> 3. 请检查是否缺少了dll文件，或者没有安装.NET框架。因为这个报错看起来似乎是某些库加载失败了。
> 4. 使用的操作系统、操作系统位数以及CPU型号。

以前fes前下的版本先开始可以用，然后一段时间没用，就这样报错，最近下了新版本也是一样，而且点确定也会重复地出现弹窗，只能在任务管理器里面关闭。
64位win10，放的D盘

**Comment by Moying-moe** [comment]
> > 比较难排查，因为看起来似乎是WPF的报错。
> > 请提供信息帮助排查：
> > 
> > 1. 是一直无法启动？还是使用以前的旧版本可以启动，更新到最新版以后不行了呢？如果曾经使用旧版本可以启动，但是在某个版本以后就无法启动了，请提供版本。
> > 2. Majdata文件夹放在哪里？比如，是否放在了系统盘。
> > 3. 请检查是否缺少了dll文件，或者没有安装.NET框架。因为这个报错看起来似乎是某些库加载失败了。
> > 4. 使用的操作系统、操作系统位数以及CPU型号。
> 
> 以前fes前下的版本先开始可以用，然后一段时间没用，就这样报错，最近下了新版本也是一样，而且点确定也会重复地出现弹窗，只能在任务管理器里面关闭。 64位win10，放的D盘

可不可以这样理解：曾经使用Beta3.1版本，可以正常使用。一段时间后再次使用Beta3.1版本，就开始报错了。随后，**无论更换什么版本**，都报错。

我比较倾向于怀疑是系统出现了一些问题，比如某些dll文件丢失。

你可以先自己检查一下，这个issue也会继续追踪。因为目前不太清楚到底是哪边出了问题。

**Comment by Moying-moe** [comment]
@LingFeng-bbben 帮忙看下

**Comment by MorningFur** [comment]
> > > 比较难排查，因为看起来似乎是WPF的报错。
> > > 请提供信息帮助排查：
> > > 
> > > 1. 是一直无法启动？还是使用以前的旧版本可以启动，更新到最新版以后不行了呢？如果曾经使用旧版本可以启动，但是在某个版本以后就无法启动了，请提供版本。
> > > 2. Majdata文件夹放在哪里？比如，是否放在了系统盘。
> > > 3. 请检查是否缺少了dll文件，或者没有安装.NET框架。因为这个报错看起来似乎是某些库加载失败了。
> > > 4. 使用的操作系统、操作系统位数以及CPU型号。
> > 
> > 
> > 以前fes前下的版本先开始可以用，然后一段时间没用，就这样报错，最近下了新版本也是一样，而且点确定也会重复地出现弹窗，只能在任务管理器里面关闭。 64位win10，放的D盘
> 
> 可不可以这样理解：曾经使用Beta3.1版本，可以正常使用。一段时间后再次使用Beta3.1版本，就开始报错了。随后，**无论更换什么版本**，都报错。
> 
> 我比较倾向于怀疑是系统出现了一些问题，比如某些dll文件丢失。
> 
> 你可以先自己检查一下，这个issue也会继续追踪。因为目前不太清楚到底是哪边出了问题。

嗯嗯就是想表达这个意思

**Comment by LingFeng-bbben** [comment]
很神秘啊 应该是缺dll了，UIAutomationTypes.dll
重装.net试一下
官方.net:[这里](https://dotnet.microsoft.com/zh-cn/download/dotnet-framework/thank-you/net472-offline-installer)
