### ISSUE TITLE
能否将NET Framework 4.x升级成NET 6以兼容Linux

### ISSUE THREAD

**Issue by 8MiYile** [LingFeng-bbben/MajdataView#79]
## Where?

(MajdataEdit / MajdataView)

## New Feature Request
title
(Please describe the new features you want to suggest.)

**Comment by SpadeLushen** [comment]
MajdataEdit使用WPF开发。除非改用.NET MAUI或Avalonia等跨平台UI框架重构，否则升级.NET框架版本并不能增加跨平台支持。
