### ISSUE TITLE
全新的bug

### ISSUE THREAD

**Issue by kaguyas** [LingFeng-bbben/MajdataView#80]
![@PSX30)$RK298C2RC%6$ NY](https://user-images.githubusercontent.com/47970253/203795593-57278c9c-f9c2-4b77-a67a-5b8ec201aa30.png)
![$OG58$@FD%N6AL997M$(5E6](https://user-images.githubusercontent.com/47970253/203795611-76f10eed-3c80-462a-b787-2f28ab3c7a44.png)
还没写完5秒就蹦出来了，原因未知 输入逗号过后就报错了。

**Comment by LingFeng-bbben** [comment]
你定义bpm和拍号了吗

**Comment by kaguyas** [comment]
> 你确定bpm和拍号了吗
当然有。。拖动下方进度就会报错 转到最后一个note拖动就不会出现错误 但在最后一个note之前无论怎样试图拉动进度条都会报错

**Comment by kaguyas** [comment]
今天出现了同样的问题，保留了相对完整的过程
**bpm拍号以及歌曲文件确认无错误**
https://user-images.githubusercontent.com/47970253/212545633-55fe8a26-138d-4811-a9ba-91620d2fa424.mp4

**Comment by kaguyas** [comment]
另一个报错:

https://user-images.githubusercontent.com/47970253/212545821-a69a12ec-d671-4a62-b699-a4e540a85d1d.mp4

**Comment by kaguyas** [comment]
关于描述的不同点在于这次出现的情况不是最后一个tap拖动不会出现这个问题，而是开头拖动时间轴不会出现任何问题 拖到第一个tap就会出现

https://user-images.githubusercontent.com/47970253/212545970-48a1d22e-b920-4ff9-bb47-60bafa4b1942.mp4
视频似乎需要下载后才能正常观看

**Comment by LingFeng-bbben** [comment]
修了，为历史遗留问题
