### ISSUE TITLE
希望录制模式节拍器可以根据wholebpm速度决定

### ISSUE THREAD

**Issue by sniper-feng** [LingFeng-bbben/MajdataView#81]
## Where?

(MajdataEdit / MajdataView)

## New Feature Request

(Please describe the new features you want to suggest.)
目前clock_count定义出的节拍器声速度是根据谱面起始bpm来定的，但是目前遇到一个麻烦，就是曲子变速很多的情况下，第一个bpm并不是主bpm。例如目前在写的歌曲，副歌bpm为140，节拍器也应该打这个速度，但是开头的bpm是60，这样节拍器打出来的就是60bpm，比较尴尬（

**Comment by LingFeng-bbben** [comment]
不支持，节拍器不就是给人找准开始的速度的吗
