### ISSUE TITLE
Increase editor size

### ISSUE THREAD

**Issue by Outpact** [LingFeng-bbben/MajdataView#82]
## Where?

MajdataEdit

## New Feature Request

Ability to scale text/application larger to make it easier to read on larger resolutions, very difficult and straining on the eye to see
 
![image](https://user-images.githubusercontent.com/6890615/205980836-d647e148-a14a-47ab-9893-3a48f2469e25.png)

**Comment by kaguyas** [comment]
click x:\Majdata-xxx \EditorSetting.json 
2.set   "FontSize": x (default:12.0)
3.save
