### ISSUE TITLE
只有break音效与slide声音

### ISSUE THREAD

**Issue by tzero-temp** [LingFeng-bbben/MajdataView#83]
下载新版本后打开旧有谱面只剩下了break和slide音效与音乐
新创谱面甚至没有音效（这个可能是个例，上面为必然）
仅仅是跟旧版常规的操作 想问问会不会是我的问题 我用的上一个版本是还没更新新fest特性的时候

**Comment by kaguyas** [comment]
更新须知:编辑器中的音量设置进行了一些修改，您在打开过去的谱面时，可能会出现正解音和判定音音量为0的情况。请您打开音量设置，重新设置正解音（Answer）和判定音（Judge）的音量，然后点击下面的“将当前音量设为默认”按钮。之后打开旧版本谱面时，可以直接点击“重置音量到默认值”按钮。

**Comment by tzero-temp** [comment]
！好的 没看清楚 不好意思 谢了
