### ISSUE TITLE
谱面播放器竖屏时显示不正常

### ISSUE THREAD

**Issue by dengxiangyu1210** [LingFeng-bbben/MajdataView#84]
## 问题出现的位置

MajdataView啦

## 问题描述

不知道怎么描述诶 详见截图……？

## 它是怎么出现的

稳定发力

## 它可以复现吗

稳定发力

## 可能有帮助的截图与文件

![QQ截图20230107104827](https://user-images.githubusercontent.com/52367076/211128109-23b949f2-98e1-4cb5-bdf8-aa56619655f0.png)

**Comment by LingFeng-bbben** [comment]
为啥竖着啊

**Comment by dengxiangyu1210** [comment]
![78XM2KCPT21)67I7~}7U4BY](https://user-images.githubusercontent.com/52367076/211131338-222b84b0-6eae-4fd8-b5f8-9a15e224dcd6.png)
因为副显示器是竖着摆的（
（其实不竖着只是在16:9的横屏下让viewer和editor分屏显示也有一点显示不全 只是这种情况不影响正常用就是了）

**Comment by LingFeng-bbben** [comment]
因为viewer是根据窗口高度适配 所以我建议你是手动把他拖成正方形用
