### ISSUE TITLE
无法联网更新，无法连接到View

### ISSUE THREAD

**Issue by yl170512** [LingFeng-bbben/MajdataView#89]
較舊的版本使用會出現這個問題(Beta3.0)
![image](https://user-images.githubusercontent.com/124447739/216772986-0b88f48a-017a-4f37-9cff-2e205c3a304d.png)

而最新的4.1.0版本則是在開啟前會出現報錯視窗
![image](https://user-images.githubusercontent.com/124447739/216773040-7ea038eb-7f6e-4f55-862c-b3fe2b065c19.png)

本人比較外行，稍微爬過文之後覺得可能是.net framework的問題
我的版本為4.8，有嘗試卸載並改安裝為4.7.2版
但由於4.8版本始終無法成功卸載而無法進行安裝4.7.2版的狀況
所以不確定是否為此問題

**Comment by LingFeng-bbben** [comment]
这两个错误都是无法联网导致的（内网和外网）。看看你的杀毒软件有没有拦截啊什么的

**Comment by yl170512** [comment]
我將系統的防火牆關閉並詳細檢查了一遍之後
確定應該不是防火牆或是防毒軟體的問題

在確認關閉完之後開啟城市依然是這個報錯通知
![image](https://user-images.githubusercontent.com/124447739/216789869-5de4ac1b-47e0-4675-8765-2456376bc386.png)

目前為檢查下來唯一不確定的是這個裝置加密作用
現在本人正在設法嘗試看看是否為此原因
![image](https://user-images.githubusercontent.com/124447739/216790040-206c264d-f49e-4190-87f4-942b85ba81c2.png)
