### ISSUE TITLE
Please open Majdataview by 强制软件渲染.bat iin the folder

### ISSUE THREAD

**Issue by KinXY** [LingFeng-bbben/MajdataView#91]
When opening an existing maidata.txt, Majdataedit.exe shows an error "Render thread failure" and suggests me to do as the title says.
However, I could not even find a .bat file in the latest released version.

**Comment by LingFeng-bbben** [comment]
sry， forgot to add the bat file

**Comment by LingFeng-bbben** [comment]
you could find one in the older releases. I will fix this in next release.
