### ISSUE TITLE
-选择音频后莫名出现报错

### ISSUE THREAD

**Issue by chuxuedachuxue** [LingFeng-bbben/MajdataView#93]
(Tips: 你可以删除小括号中的内容，这些内容只是提醒你应该写什么的)

## 

(Majdata在选完音频后读取不了音频)

## 问题描述

(选择并打开后显示不出音频也播放不了)

## 它是怎么出现的

(如上)

## 它可以复现吗

(一直如此)

## 可能有帮助的截图与文件

(请上传出现问题时的截图。如果可以的话，您最好将您的谱面打包上传)
![QQ图片20230213203803](https://user-images.githubusercontent.com/125273626/218459768-a19d46ac-f8c9-42a8-920e-0f3793b8df62.jpg)
![QQ图片20230213203810](https://user-images.githubusercontent.com/125273626/218459796-49d252d9-7355-4b7a-8a8f-20dde8ad3add.jpg)

**Comment by LingFeng-bbben** [comment]
试一下软件渲染
