### ISSUE TITLE
点击播放键后无法加载背景视频和图片,也无法播放谱面,但可以播放音乐

### ISSUE THREAD

**Issue by Stbanco** [LingFeng-bbben/MajdataView#94]
## 问题出现的位置
我不清楚哪个出现了问题，或是两者都出现了问题
(是MajdataEdit——也就是谱面编辑器——出现了问题，还是MajdataView出现了问题，亦或是二者都出现了问题呢？)

## 问题描述

点击播放键后没有播放谱面，也不加载背景视频和封面，但音乐可以正常播放。
## 它是怎么出现的

我在第70行写下[6-1[3:1],]后点击了播放键，但并未从我设定的位置播放，而是从头播放（此时背景视频和谱面还可以加载），但我重启软件后就无法加载谱面和视频了，但音乐可以正常播放。

## 它可以复现吗

可以。我重启我的设备并关闭杀毒软件后问题依然存在。

## 可能有帮助的截图与文件

如果视频无法播放，麻烦将后缀名改为.mkv

https://user-images.githubusercontent.com/126374862/221395272-737fc643-31a9-4cdf-a8d5-32d2e398e2aa.mp4

为了减小zip体积，我只压缩了track.mp3和maidata.txt
[青芽.zip](https://github.com/LingFeng-bbben/MajdataView/files/10833149/default.zip)

**Comment by Grizzfured** [comment]
语法写错了吧

**Comment by LingFeng-bbben** [comment]
你在用一些很神秘的新语法
找点大家写好的谱看看吧
