### ISSUE TITLE
关于内录视频导出失败的BUG

### ISSUE THREAD

**Issue by CHAyoooo** [LingFeng-bbben/MajdataView#99]
(Tips: 你可以删除小括号中的内容，这些内容只是提醒你应该写什么的)

## 问题出现的位置

MajdataEdit

## 问题描述

使用内录导出视频时报错，提示“未将对象引用设置到对象的实例。发生一个或多个错误”，此时回到编辑器中点击播放键只会播放all perfect动画，拖动进度条后谱面可重新正常播放

## 它是怎么出现的

点击导出视频后，设置分辨率为1080p/720p，点击确定，出现该情况

## 它可以复现吗

可复现

## 可能有帮助的截图与文件

(请上传出现问题时的截图。如果可以的话，您最好将您的谱面打包上传)
![屏幕截图 2023-03-27 135131](https://user-images.githubusercontent.com/129034727/227855053-ee8395a9-6549-4a1b-8e99-bf87466e7e92.png)

**Comment by LingFeng-bbben** [comment]
请更新到4.2.0
